### PR TITLE
Refactor for parallelization

### LINKED ISSUE #7: Merge p file functionality
@mousebrains, I understand the need for the merge p file functionality. I would like to understand how this works given that it is not always required. How much overhead does it add to the code to run every time? Does it cache the results for future speed ups? It could be made optional if there is significant overhead.

https://github.com/jessecusack/perturb/blob/main/Code/merge_all_p_files_in_directory.m

### LINKED ISSUE #9: Break down package entry points (and processing steps)
The main entry point this package for end users is the function `process_VMP_files`, which wraps all the processing steps together. There are many occasions where someone might want to process a single p file (or even a single profile), without creating a whole new folder structure. I think we need to unwrap the processing steps and make them accessible to users.

### LINKED ISSUE #15: p files flagged
I'm trying to run perturb on the glider p files and the `qUse` parameter is set to false somewhere, so none of the p files are processed. I cannot yet figure out why... 

Ok, it was because `my_joiner` prefers the rhs table over the lhs and for some reason the rhs table was full of `qUse = false`. The rhs is loaded from `info.p2mat_filename`... I am not sure how or when this was created with so many falses.

### LINKED ISSUE #16: create noise flag instead of dropping epsilon
I think that the appropriate way to handle epsilon values close to the instrument noise floor is to create a true/false QC variable, not to convert estimates to NaN. This would be the transparent way to handle QC and allows for the adding of additional QC flags in the future. 

The parameter `diss_epsilon_minimum` should be renamed to something like `epsilon_noise_floor`.

### LINKED ISSUE #17: Make parallel processing optional
@mousebrains, what do you think about adding an optional flag for parallel processing and throwing in a parfor loop somewhere? I know that some users may not have the right toolbox, but for those that do, it could speed things up immensely. I believe that batch processing of independent p / mat files qualifies as an 'embarrassingly' parallel problem.

### LINKED ISSUE #18: Random string in folder name
@mousebrains can you remind me why we append a random string to some of the output filenames?

### LINKED ISSUE #20: Epsilon estimated from separate shear probes in binned data?
It seems that the binned data (and therefore the combo netcdf) does not contain separate estimates of epsilon from the two shear probes. I haven't figured out where they get dropped, but they should be outputted. How would we change this?

### LINKED ISSUE #24: bottom depth?
Variable `bottomDepth` seems to be calculated even for data where the bottom crasher was not used (i.e. glider).

### PR DESCRIPTION
**Pull request by mousebrains**
A refactoring of the code, which includes support for the Parallel Computing Toolbox.

The single threaded refactoring is ~20-30% faster.

On my 10 core M1 MacBook the wall clock time for a parallelized job is about 15-25% of the single threaded job.

### CODE REVIEW

**Comment by jessecusack** [comment]
@mousebrains, excellent. What issues doe the refactor cover? Have you reduced the processed file sizes?  Is the parallel aspect optional?

**Comment by mousebrains** [comment]
There is a CHANGELOG.md that starts to describe some of the changes.

No, the parallelization is not "optional." If you don't have Matlab's "Parallel Computing Toolbox," the code will run as a single process. If you do have Matlab's "Parallel Computing Toolbox," the code will start a ProcessPool, using the configuration the user has set, or Matlab determines. It is on my pallet to sort out how to have the "Parallel Computing Toolbox" installed, but to force parfor to not use it. But that is a low priority for now.

The file sizes are smaller, but only ~20%. Part of deep dive after getting the NetCDF file generation restored is to dig through each of the generated files and see what I want to keep/add/subtract. I'm very hesitant to change the output of odas_p2mat, but to save space I'll have to. The profiles are where I can potentially save the most space, but I want enough to debug the spectra.

**Comment by jessecusack** [comment]
@mousebrains we should use an arithmetic mean on the non-logarithmic values of epsilon when binning dissipation. Averaging the logarithms and then exponentiating is equivalent to computing the geometric mean. The geometric mean is not physical because it doesn't conserve energy. 

Consider a 1 m3 volume of water labelled V1 and an adjacent 1 m3 of water labelled V2. Assume the dissipation rate of TKE in V1 is e1 = 1e-6 W/kg and in V2 is e2 = 1e-7 W/kg. Assume the density of this water is rho = 1000 kg/m3. The amount of energy dissipated in the total volume V1 + V2 in 1 second is e1 * rho * V1 + e2 * rho * V2 = 0.0011. If we average the dissipation rate using an arithmetic mean and do the same calculation, we get the same answer: 1/2 * (e1 + e2) * rho * (V1 + V2) = 0.0011. If we use the geometric mean, we get a different answer sqrt(e1*e2) * rho * (V1 + V2) =  6.3246e-04. If the volumes or densities of these two water masses were different, we'd need to use a weighted mean. In any case, the geometric mean does not give the right answer for the amount of energy dissipated!

By a similar argument, we should not be using the median to bin any data.

**Comment by mousebrains** [comment]
We'll have to have a discussion about this.

I understand your argument, and it makes sense when considering two different volumes.

At the shear probe level, we are measuring the same volume with two different sensors. To estimate the "true" value, it is easiest mathematically to work in the space where the distribution is normal. In this case, that is log normal. We're not trying to conserver energy, rather estimate the "true" energy.

Now for the caveat to what I say. To get the dissipation we're taking a lot of samples and calculating a spectrum over a volume of water, which we then use the Nasmyth curves to estimate the dissipation. 

For binning, I'm fine with taking the arithmetic mean, but I'm pretty sure we'll want the geometric mean between shear probe dissipation estimates.

**Comment by mousebrains** [comment]
On median/mean, I give the user the option. For someone who deals with robust statistics, they want median, for others, they want mean. Having come out of a very noisy non-normal world, I believe very strongly in robust statistics.

**Comment by jessecusack** [comment]
Ok great that we're agreed on arithmetic mean for depth binning!

Averaging across simultaneous shear probe measurements is different, like you say, so I am prepared to believe that the goemetric mean might be appropriate in that case. Does Rolph address this in one of his paper?

As for median vs. mean. We should make the mean the default setting, since it is physical and we anticipate this package being used by physical oceanographers. I understand the worry about outliers, but we should be dealing most of that problem using despiking methods + thermal lag / mass corrections on the raw data (which I know we do already). By the way, do we despike raw conductivity? If not, I think we should...

**Comment by mousebrains** [comment]
All depth binning is done with the user specified method, which now defaults to mean. I still need to figure out how to deal with CTD time binning. CTD time binning is switch from using median to mean.

I added two papers. by Rolf in to the Papers directory that address the statistics of epsilon samples. I have implemented a prior version of the mathematics, but I need to update it for Rolf's current thinking.

No, JAC_C nor JAC_T are currently despiked. If you want to look at that using VMP data, that would be useful. There are two places this should happen, one in the mat2profile.m code and another in the ctd2binned.m code.

I have checking this branch the updates.

**Comment by mousebrains** [comment]
Resolve bottom depth?

**Comment by mousebrains** [comment]
#24 Fixed by update to bottom_crash_profiles.m

**Comment by jessecusack** [comment]
Please 'squish' merge this whenever you are ready @mousebrains. I connect a bunch of issues which should be auto-closed with the merge.

**Comment by mousebrains** [comment]
Push to main branch

**Pull request closed without merging**
